[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "easyfigs"
version = "0.0.1"
dependencies = [
    "numpy",
    "matplotlib",
]

[tool.setuptools]
packages = ["easyfigs"]
